package com.example.demo.api;

import com.example.demo.applicationdb.BCrypt;
import com.example.demo.db.UserRepository;
import com.example.demo.model.User;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.ResponseBody;
import org.springframework.web.bind.annotation.RestController;


@RestController // This means that this class is a Controller
@RequestMapping(path="/api/users")
public class UserController {
    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
  private UserRepository userRepository;

  /**
   * Add new user and generate hash password
   * @param user
   */
  @PostMapping(path="/add") // Map ONLY POST Requests
  public void addNewUser (@RequestBody User user) { 
    
    user.setPassword(BCrypt.hashpw(user.getPassword(), BCrypt.gensalt(12)));
    
    userRepository.save(user);
  }

  @GetMapping(path="/all")
  public @ResponseBody Iterable<User> getAllUsers() {
    // This returns a JSON or XML with the users
    return userRepository.findAll();
  }  
}